In [ ]:
#Daily Exercises

In [ ]:
#Exercise 1

import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Exercise 2

import numpy as np
alist = [3.14, 0, 1, 2]
arr2 = np.array(alist)
arr_int = arr2.astype(int)
print(arr_int)

[3 0 1 2]


In [9]:
#Exercise 3

import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Exercise 4

import random
import numpy as np

np.random.seed(42)
random_array = np.random.random((4,5))
print(random_array.round(2))


[[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]]


In [12]:
#Exercise 5

import numpy as np
# Define the array
array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

# Select the second row (index 1)
second_row = array[1]

print(second_row)

[20 21 22 23 24]


In [13]:
#Exercise 6

import numpy as np

arr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
reversedarr = arr[::-1]
print(reversedarr)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#Exercise 7

import numpy as np

print("4x4 identity:")
print(np.eye(4))
print()

4x4 identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [15]:
#Exercise 8

import numpy as np

# A 1D array containing numbers 0 through 9
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calculate sum and average (mean)
total_sum = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total_sum}, Average: {average}")

Sum: 45, Average: 4.5


In [17]:
#Exercise 9

import numpy as np
arr = np.arange(1, 21)
matrix = arr.reshape(4,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
#Exercise 10

import numpy as np
arr3 = np.arange(1, 11)
print(f"Odd numbers:   {arr3[arr3 % 2 == 1]}")

Odd numbers:   [1 3 5 7 9]
